# generated by datamodel-codegen:
#   filename:  api.yml
#   timestamp: 2023-05-28T12:18:29+00:00

from __future__ import annotations

# Standard Library
from typing import List

# Third Party Library
from pydantic import BaseModel


class ScoreRequest(BaseModel):
    username: str
    value: int


class ScoreResponse(BaseModel):
    id: int
    username: str
    value: int


class ScoresResponse(BaseModel):
    __root__: List[ScoreResponse]


class Error(BaseModel):
    code: int
    message: str
