# generated by datamodel-codegen:
#   filename:  api.yml
#   timestamp: 2023-05-28T09:17:28+00:00

from __future__ import annotations

# Standard Library
from typing import List

# Third Party Library
from pydantic import BaseModel


class Score(BaseModel):
    id: int
    username: str
    value: int


class Scores(BaseModel):
    __root__: List[Score]


class Error(BaseModel):
    code: int
    message: str
